logLevel: "info"
readBufferSize: 2048
challengeTTL: 60
rateLimitGlobal: 25
rateLimitGlobalBurst: 333
rateLimitClient: 150
rateLimitClientBurst: 5
serverInfoUpdateTimeout: 550ms
serverInfoUpdateInterval: 20
servers:
  "sv1": 
    "ip": "127.0.0.1"
    "port": "27015"
    "engine": "goldsrc"
