logLevel: "info"
readBufferSize: 2048
challengeTTL: 60
rateLimitGlobal: 25
rateLimitGlobalBurst: 333
rateLimitClient: 150
rateLimitClientBurst: 5
serverInfoUpdateTimeout: 550ms
serverInfoUpdateInterval: 30
servers:
  "sv1": 
    "ip": "216.52.148.19"
    "port": "27016"
    "engine": "goldsrc"
  "sv2":
    "ip": "162.248.92.111"
    "port": "27017"
    "engine": "goldsrc"